# .streamlit/secrets.toml

[salesforce]
username = "your_salesforce_username"
password = "your_salesforce_password"
security_token = "your_salesforce_security_token"
domain = "login"  # Use 'test' for sandbox environments

[azure]
api_key = "your_azure_api_key"
base_url = "https://your_azure_openai_endpoint"
api_version = "2024-08-01-preview"
